# BuildPortraitCatalog.py - writes assets/portraits/portraits.cat from the tag
# tables that sit beside the archived portrait packs.
#
#   python tools\BuildPortraitCatalog.py
#
# Each SOURCE (the table below) is a bought pack archived in
# OneDrive\DungeonAssets\ui\<folder>\ with a tags.tsv beside its zips: one row
# per portrait, file / race / sex / age / look / framing / uncertain, where
# `file` is already the portrait's id. The tags were made by eye from contact
# sheets (docs/portraits-notes.md); this script is the record of how they become
# the catalog, so a re-tag is an edit to a table and a re-run. A source whose
# table does not exist yet is reported and skipped.
#
# FRAMING decides what ships: a full-body figure's face is too small to read in
# a party slot, so figures are left out here, and since tools\FetchPortraits.ps1
# extracts exactly the ids this catalog lists, they never reach assets/portraits.

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "assets", "portraits", "portraits.cat")
ARCHIVE = os.path.join(os.environ.get("OneDrive", os.path.join(os.path.expanduser("~"), "OneDrive")),
	"DungeonAssets", "ui")

# name -> archive folder. The name is written as each entry's `source`.
# FetchPortraits.ps1 keeps the matching table of zips.
SOURCES = [
	("magory", "magory-fantasy-portraits"),
	("corax", "corax-human-heroes"),
]

# Byte-identical files inside a pack (sha1-matched when Corax was tagged): the
# second copy of each pair is left out, so the picker never shows one face twice.
DUPLICATES = {
	"corax239": "corax236", "corax240": "corax237", "corax241": "corax238",
	"corax312": "corax309", "corax313": "corax310", "corax314": "corax311",
}

FIELDS = ("race", "sex", "age", "look")
VOCAB = {
	"race": {"human", "elf", "dwarf", "orc", "undead", "demon", "other"},
	"sex": {"male", "female", "unclear"},
	"age": {"young", "adult", "old", "unclear"},
	"look": {"warrior", "rogue", "mage", "cleric", "noble", "commoner"},
	"framing": {"face", "bust", "figure"},
}
COLUMNS = ["file", "race", "sex", "age", "look", "framing", "uncertain"]

HEADER = """\
; Party portraits, from the bought packs in docs/costs.md: one [id] per image in
; assets/portraits/<id>.png (.dds beside it). GENERATED by
; tools\\BuildPortraitCatalog.py from each pack's tags.tsv in the archive - edit
; a table and re-run rather than editing this file. The images are not in git:
; tools\\FetchPortraits.ps1 extracts the ids listed here.
;
; Fields (tagged by eye; the portrait picker filters on race / sex / age):
;   source    the pack: magory (Magory, Fantasy Character Portraits Pack) |
;             corax (Corax Digital Art, 500 Human Hero portraits - its license
;             requires a credit, see docs/costs.md Attributions)
;   race      human | elf | dwarf | orc | undead | demon | other
;   sex       male | female | unclear
;   age       young | adult | old | unclear
;   look      warrior | rogue | mage | cleric | noble | commoner, '+' joins two.
;             Most portraits are face crops with no gear in frame, so this is
;             mostly 'commoner' and nothing filters on it yet.
;   uncertain the fields above that were a guess (absent = none)
"""


def read_source(name, path, seen):
	lines = open(path, encoding="utf-8").read().splitlines()
	head = [h.strip() for h in lines[0].split("\t")]
	if head != COLUMNS:
		sys.exit(f"{path}: unexpected header {head}")
	blocks, dropped, dupes = [], 0, 0
	for n, line in enumerate(lines[1:], start=2):
		if not line.strip():
			continue
		c = [x.strip() for x in line.split("\t")]
		if len(c) != len(COLUMNS):
			sys.exit(f"{path}:{n}: expected {len(COLUMNS)} columns, got {len(c)}")
		rec = dict(zip(COLUMNS, c))
		for f in FIELDS + ("framing",):
			vals = rec[f].split("+") if f == "look" else [rec[f]]
			if not all(v in VOCAB[f] for v in vals):
				sys.exit(f"{path}:{n}: bad {f} '{rec[f]}'")
		if rec["file"] in seen:
			sys.exit(f"{path}:{n}: duplicate id {rec['file']} (also in {seen[rec['file']]})")
		seen[rec["file"]] = name
		if rec["file"] in DUPLICATES:
			dupes += 1
			continue
		if rec["framing"] == "figure":
			dropped += 1
			continue
		block = [f"[{rec['file']}]", f"source = {name}"] + [f"{f} = {rec[f]}" for f in FIELDS]
		if rec["uncertain"] != "-":
			block.append(f"uncertain = {rec['uncertain']}")
		blocks.append("\n".join(block))
	return blocks, dropped, dupes


def main():
	blocks, seen = [], {}
	for name, folder in SOURCES:
		path = os.path.join(ARCHIVE, folder, "tags.tsv")
		if not os.path.exists(path):
			print(f"{name}: no tags yet ({path}) - skipped")
			continue
		got, dropped, dupes = read_source(name, path, seen)
		blocks += got
		print(f"{name}: {len(got)} portraits ({dropped} figures, {dupes} duplicates left out)")
	missing = [d for d in DUPLICATES.values() if d not in seen]
	if seen and any(k in seen for k in DUPLICATES) and missing:
		sys.exit(f"a duplicate's original is not tagged: {missing}")

	if not blocks:
		sys.exit("no portraits - nothing written")
	os.makedirs(os.path.dirname(OUT), exist_ok=True)
	# CRLF: .gitattributes pins *.cat to it (the game writes catalogs that way).
	with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
		f.write(HEADER + "\n" + "\n\n".join(blocks) + "\n")
	print(f"{len(blocks)} portraits -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
	main()
